### ISSUE TITLE
Unexpected token v2.1.0

### ISSUE THREAD

**Issue by miralize** [nuxt/vue-meta#418] opened 2019-07-25 11:59 UTC
Seeing an error on line 531 of vue-meta.common.js, due to the spread operator not being transpiled properly

![image](https://user-images.githubusercontent.com/1761115/61872716-0287c080-aedc-11e9-83ab-189b5ca4f94e.png)

Any help would be greatly appreciated

**Comment by pimlie** [comment] 2019-07-25 12:09
Could you share a bit more info about your project? Do you use vanilla Vue or a framework like Nuxt?

Also you mention the cjs build, but the screenshot shows the esm build...

**Comment by miralize** [comment] 2019-07-25 12:19
Ah sorry that was a wrong screengrab by me. I was trying both imports. Our project is using vue natively yep. 2.6.10

**Comment by pimlie** [comment] 2019-07-25 12:32
Could you please create a reproduction? I cannot reproduce this with the examples build / app

**Comment by rockvcp** [comment] 2019-07-26 03:07
> Ah sorry that was a wrong screengrab by me. I was trying both imports. Our project is using vue natively yep. 2.6.10.
> 
> I get the same error with cjs though

Got similar issue on vue-meta v2.1.0:
![image](https://user-images.githubusercontent.com/4480007/61923136-72a64d00-af95-11e9-85ae-e629062a8ae8.png)
any workaround on this?

**Comment by rockvcp** [comment] 2019-07-26 03:25
I found out the version 1.5.5 is working perfectly fine.
Add this to your package-lock.json:
`"vue-meta": {
      "version": "1.5.5",
      "resolved": "https://registry.npmjs.org/vue-meta/-/vue-meta-1.5.5.tgz",
      "integrity": "sha512-DJLmAnuHexTk7+zxMcvmTqMEyil+sdeu67yLH6ajxFG/KTuYNnzX+qOkv6BiVgt21KYV8fw2H8aaLjfhQ7fG5w==",
      "requires": {
        "deepmerge": "^2.0.0",
        "lodash.isplainobject": "^4.0.6",
        "object-assign": "^4.1.1"
      }
    },`

and add this to your package.json 
`"vue-meta": "^1.5.5",`

lastly try npm i

**Comment by pimlie** [comment] 2019-07-26 07:11
@rockvcp Without a reproduction I am unable to dig deeper into this, please take the time to share a reproduction so we can look into this and fix this behaviour

The vue-meta examples are also a native Vue app built with webpack but that seems to work fine. Also its very strange you are using the esm build but apparently dont have support for spread syntax. Might be something in your webpack configs but no idea what.

**Comment by NCJasper** [comment] 2019-07-26 11:59
I had a similar issue today. Turned out I had to update `@babel/core` to 7.5.5

**Comment by miralize** [comment] 2019-07-26 12:14
Ah were stuck on babel 6 currently. We cant upgrade as we dont have control of our build system (multiple products using the same thing).

**Comment by pimlie** [comment] 2019-07-26 15:47
My bad guys, babel was missing a valid config for the rollup build. Should be fixed with v2.1.1

**Comment by miralize** [comment] 2019-07-26 15:50
No worries @pimlie :) Apologies I couldn't find the time to repro

**Comment by deraw** [comment] 2019-07-29 08:53
I had this issue on IE, with the latest versions it's fixed! Thanks @pimlie :)

**Closed** 2019-07-29 10:19 UTC
Labels: needs reproduction
