### ISSUE TITLE
Need to add comment to header

### ISSUE THREAD

**Issue by jacstrong** [nuxt/vue-meta#375] opened 2019-06-03 18:56 UTC
### What problem does this feature solve?

There was a question a while back similar to this about adding a 
<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9305">#c9305</a>)</em></sub></div>

**Comment by pimlie** [comment] 2019-06-04 18:37
Thanks, in that case then this is a duplicate of 241 and can be closed :)

**Closed by pimlie** 2019-06-04 18:37 UTC
Labels: duplicate
