### ISSUE TITLE
returning nothing make the app bug silently

### ISSUE THREAD

**Issue by ScreamZ** [nuxt/vue-meta#297] opened 2018-12-18 11:01 UTC
Hello,

I'm using nuxt which is using vue-meta with a head object.

If you do the following, this break interface silently : 

```js
head() {
    return;
}
```

instead you have to do the following

```js
head() {
    return null;
}

// OR

head() {
    return {};
}
```

I think add a check for this and dispatch at least a console warning could be nice.

Regards :)

**Comment by manniL** [comment] 2019-01-24 23:05
Not sure if the bug is still present.

**Comment by pimlie** [comment] 2019-03-07 18:29
I am quite sure this is a duplicate of #279 (or at least this is a cause of that issue), will close it as such.

**Closed by pimlie** 2019-03-07 18:29 UTC
Labels: PR Welcome, bug
