### ISSUE TITLE
html attribute value repeated with ssr

### ISSUE THREAD

**Issue by cheungmk** [nuxt/vue-meta#541] opened 2020-04-09 04:26 UTC
Reproduce:

using htmlAttrs with ssr

app.vue
```
  metaInfo: {
    htmlAttrs: {
      lang: 'en'
    }
  }
```

html tag: server rendered
```
<html
  data-vue-meta-server-rendered
  lang="en"
  data-vue-meta="%7B%22lang%22:%7B%22ssr%22:%22en%22%7D%7D"
>
```

html tag: after browser rendered
```
<html data-vue-meta-server-rendered="" lang="en en">
```

the value of lang is repeated

playground:
https://codesandbox.io/s/flamboyant-shannon-9qk6z
https://9qk6z.codesandbox.io/

**Comment by roccojanse** [comment] 2020-04-22 11:43
+1 please fix asap

**Comment by Quaberti** [comment] 2020-04-23 13:48
+1 please fix asap

**Comment by manniL** [comment] 2020-04-23 15:18
Writing "+1 please fix asap" **doesn't help** anyone nor resolves the issue magically quicker.

**Comment by pimlie** [comment] 2020-04-25 10:56
Could someone make a reproduction of this with the code from `examples/ssr`? Unfortunately I cannot reproduce this.

From the info posted in the op, the problem seems to be that somehow vue-meta hydration failed as the `data-vue-meta-server-rendered` is still being listed and it should be removed when vue-meta hydrates. But how/why this occurs isnt clear to me

**Comment by cheungmk** [comment] 2020-04-27 06:27
I found the issue is occur when using `render` to creating vue instance

```
  const app = new Vue({
    router,
    render: h => h(App)
  })
```

Reproduce for `example/ssr`
[App.js](https://gist.github.com/cheungmk/bba855561115ba48530f9b013150b426)

**Comment by tomphilpotts** [comment] 2020-05-25 12:33
Any update on a fix? Having the same issue.

`<html data-n-head-ssr lang="en" amp data-n-head="%7B%22lang%22:%7B%22ssr%22:%22en%22%7D,%22amp%22:%7B%22ssr%22:true%7D%7D">`

nuxt.config.js

```
 head: {
        htmlAttrs: {
            lang: 'en',
            amp: true
        },
...
}

```

**Comment by pimlie** [comment] 2020-05-26 21:07
@cheungmk Thanks for the repro!

This should be fixed in `v2.3.4`

**Closed by pimlie** 2020-05-26 21:07 UTC
Labels: bug, needs reproduction

**Comment by roccojanse** [comment] 2020-06-02 20:22
> Writing "+1 please fix asap" **doesn't help** anyone nor resolves the issue magically quicker.

@manniL I'm sorry, you are right. Excuse me. I was hitting a go-live deadline and this bug appeared. I saw it was labelled as bug after a few days, but after that no updates, so i wanted to let the members/maintainers know that at least someone was waiting for a fix :) wasn't trying to be rude.

**Comment by szduda** [comment] 2020-07-22 10:42
Updating the version didn't work for me, html tag attributes still have doubled content. :(

However...
the workaround that works for me is manually setting encoded json as `data-vue-meta`. I have only removed the `en` value as it was the part being appended (and shouldn't).
```<html data-vue-meta="%7B%22lang%22:%7B%22ssr%22:%22%22%7D%7D" {{{ meta.inject().htmlAttrs.text() }}}>```
