### ISSUE TITLE
Typescript compiler fails when using metaInfo() function

### ISSUE THREAD

**Issue by nomadoda** [nuxt/vue-meta#340] opened 2019-03-29 19:23 UTC
I would like to access component data from `metaInfo()` function, but typescript compiler throws me an error:

```
export default Vue.extend({
  metaInfo() {
    return {
      title: this.name,
    };
  },
  data() {
    return {
      name: 'Bob',
      country: 'Sweden',
    };
  },
  methods: {
    sayHi() {
      console.log('Hi ' + this.name + ' from ' + this.country);
    },
  },
});
```

> Property 'name' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<Record<never, any>>>'.

> Property 'name' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<Record<never, any>>>'.

> Property 'country' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<Record<never, any>>>'.

Notice that the compiler also outputs errors in the `sayHi` method. The errors only occurs when using `this` in the `metaInfo()` function

**Comment by pimlie** [comment] 2019-03-29 23:03
Do you have your own types defined so typescript nows name, country are valid properties (and what their type should be)?

When I try your example it also throws an error when I use something like `return this.name` in `sayHi`

**Comment by nomadoda** [comment] 2019-03-30 07:30
Just using default typescript setup, it should know data property types. Only when I use `this` in `metaInfo()` compiler doesn't know data properties. I could perhaps make a small repository.

**Comment by pimlie** [comment] 2019-04-20 12:39
Please also check the just released v2.0 release candidate as that has a lot of typescript improvements as well

**Comment by georgeboot** [comment] 2019-05-10 11:13
Same error here, both on `1.x` and `2.0.0-rc.1`.

I have the following `Home.vue` (created using `vue-cli` 3):
```vue
<template>
    <div class="home">
        <img alt="Vue logo" src="../assets/logo.png" />
        <HelloWorld msg="Welcome to Your Vue.js + TypeScript App" />
    </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'
import HelloWorld from '@/components/HelloWorld.vue' // @ is an alias to /src

@Component({
    components: {
        HelloWorld,
    },
    metaInfo() {
        return {
            title: 'Homepage Title',
            titleTemplate: null,
        }
    },
})
export default class Home extends Vue {}
</script>
```

My `vscode` lints the `components` section with the following error:
```json
{
	"resource": "/path/to/project/src/views/Home.vue",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type '{ components: { HelloWorld: typeof HelloWorld; }; metaInfo(): { title: string; titleTemplate: null; }; }' is not assignable to parameter of type 'VueClass<Vue>'.\n  Object literal may only specify known properties, but 'components' does not exist in type 'VueClass<Vue>'. Did you mean to write 'component'?",
	"source": "Vetur",
	"startLineNumber": 13,
	"startColumn": 5,
	"endLineNumber": 15,
	"endColumn": 6
}
```

**Comment by pimlie** [comment] 2019-05-10 15:10
@georgeboot I am not too experienced with TS but your error is about `components`, so why do you believe there is an issue with vue-meta?

**Comment by georgeboot** [comment] 2019-05-16 14:21
@pimlie when I remove the `metaInfo()` section, it works fine. Just as the reporter of this issue reports.

**Comment by manniL** [comment] 2019-05-17 09:03
Maybe @kevinmarrec can help out? :relaxed:

**Comment by kevinmarrec** [comment] 2019-05-17 09:11
@georgeboot Do you have `vue-meta` under `types` array property in `tsconfig.json` ? It's needed to tell TypeScript to look for `vue-meta` types and correctly extend Vue Component options with `metaInfo`.

```json
{
  "compilerOptions": {
    "types": [
      "vue-meta"
    ]
  }
}
```

**Comment by kevinmarrec** [comment] 2019-05-17 09:17
@nomadoda To access and have typed `this` the only way is to have an external interface that has the shape of your data 

```ts
interface MyData {
  prop: boolean
}
```
and then do
```
metaInfo(this: MyData) {}
```

It works better with Class components where you just have to do `(this: MyClass)`

**Comment by kevinmarrec** [comment] 2019-06-07 10:08
@nomadoda @georgeboot Is there still an issue ?

**Comment by georgeboot** [comment] 2019-06-07 10:08
@kevinmarrec I did not, added it now. But no luck, still getting the same linting warning.

**Comment by kevinmarrec** [comment] 2019-06-07 10:13
@georgeboot Can you try restarting VSCode (it happens often that `tsconfig.json` change need a restart)

**Comment by georgeboot** [comment] 2019-06-07 10:14
@kevinmarrec tried that as well but doesn't resolve the issue.

Can you reproduce my issue?

**Comment by kevinmarrec** [comment] 2019-06-07 10:25
@georgeboot I'm not using VueCLI so please provide a repository with the issue and I'll try to fix it

**Comment by georgeboot** [comment] 2019-06-07 10:56
@kevinmarrec Please check: https://github.com/georgeboot/eslint-error-with-vue-meta-demo/blob/master/src/App.vue#L13-L21

It's a fresh vue-cli project with minimal options (only TypeScript and eslint) and vue-meta 2.0.0-rc.2 installed.

**Comment by kevinmarrec** [comment] 2019-06-07 11:58
@georgeboot I found your issue.

TypeScript does not display the correct error, the error is that `titleTemplate` can't be null are you're setting it to null : https://github.com/nuxt/vue-meta/blob/master/types/vue-meta.d.ts#L115

**Comment by kevinmarrec** [comment] 2019-06-07 12:03
The main topic of this Github issue is resolved https://github.com/nuxt/vue-meta/issues/340#issuecomment-493384790. So i'm closing it.

**Closed by kevinmarrec** 2019-06-07 12:03 UTC
Labels: question, typescript

**Comment by UstymUkhman** [comment] 2019-09-05 13:42
I'm also having this issue today. In my case, the problem seems to be `base: { href: '/' }` in the `metaInfo`'s return object and `{ 'http-equiv': 'X-UA-Compatible', content: 'IE=edge' }` in the `meta` array. Don't' know why though.

**Comment by BonBonSlick** [comment] 2020-05-20 16:33
I am using class component, there are no errors, it just does not work https://github.com/nuxt/vue-meta/issues/144#issuecomment-631580608

**Comment by BonBonSlick** [comment] 2020-05-20 16:48
Please update documentation

**Comment by williamthorsen** [comment] 2020-08-31 02:24
I had the same error and was able to resolve it without declaring an interface:

```typescript
import { MetaInfo } from 'vue-meta';

export default Vue.extend({
  metaInfo(): MetaInfo {
         // ^ Add the return-value type
  ...
```
