### ISSUE TITLE
[QUESTION] How to load webpacked images in assets folder in vue meta?

### ISSUE THREAD

**Issue by dysol** [nuxt/vue-meta#233] opened 2018-07-11 10:37 UTC
Hi,
how do i load my images in /assets folder with vue-meta?

```
{ hid: 'og:image', name: 'og:image', content: require('~/assets/img/home/bri-booklet.jpg') },
```
doesn't seem to work. Any help?

**Comment by canyoudev** [comment] 2018-07-12 16:05
You don't need to **load** images in meta tags, bud

**Comment by dysol** [comment] 2018-07-13 08:11
@canyoudev i meant webpacked images. Not static images where i can just state the /path/to/img

**Comment by oahccc** [comment] 2018-08-26 18:26
Hi @dysol,

In the script tag, you could
`import ogImage from "./assets/img/home/bri-booklet.jpg"`

and then use it as below
`{ hid: 'og:image', name: 'og:image', content: "https://your.domain" + ogimage},`

**Comment by ricardovigatti** [comment] 2018-12-13 18:20
try again using functions and return your require('~/assets/img/home/bri-booklet.jpg')

**Comment by ricardovigatti** [comment] 2018-12-14 00:01
Sorry, what I have said above didn't work... I've tried using base64 image, but I'm still looking for better approaches.

**Comment by pimlie** [comment] 2019-04-23 15:07
Just tried with one of the examples and @oahccc solution seems to work just fine (with file-loader configured in the webpack config for image files). That might very well be due to webpack updates since this issue was originally posted, but closing it for now. Please reopen or create a new issue with a reproduction if a problem still exists

**Closed by pimlie** 2019-04-23 15:07 UTC
Labels: question
