### ISSUE TITLE
Performance issue on destroy?

### ISSUE THREAD

**Issue by edwh** [nuxt/vue-meta#443] opened 2019-08-30 11:28 UTC
I'm fairly new to Vue, and I'm using Nuxt.  I have an app where it is slow to move to a new route.  Profiling in Chrome, I can see a lot of time being spent here:

![image](https://user-images.githubusercontent.com/56696/64017252-0cc35d00-cb21-11e9-8cca-7fb4016503cd.png)

Digging deeper:

![image](https://user-images.githubusercontent.com/56696/64017273-1baa0f80-cb21-11e9-9959-a52ab1f9c75c.png)

To me this looks as though every time a Vue component is destroyed, an interval timer will be created.  I could be wrong.

If many components are destroyed at the same time (e.g. on routing to a new page), it would create a lot of these timers.  Generally I've found that it is better to start a single interval timer that checks a queue rather than create a lot of separate interval timers, because once you have a zillion timers your browser thrashes processing them all.

As I say, I might be misunderstanding what vue-meta is doing here.  Has anyone seen anything similar?

**Comment by edwh** [comment] 2019-08-30 11:35
If I hack out this setInterval code then my performance issue goes away, so that does seem to be the issue.

**Comment by pimlie** [comment] 2019-08-30 11:39
Thanks for the report, I think this is a duplicate of #442.

I tracked the memory leak down to the destroy function indeed, but dont have a proper fix ready yet. Will close this issue in favor of #442

**Closed by pimlie** 2019-08-30 11:39 UTC
Labels: duplicate

**Comment by edwh** [comment] 2019-08-30 11:41
Thanks for the extremely quick reply, I'll subscribe to that issue.

If possible, avoiding a per-component timer would definitely help performance.

**Comment by pimlie** [comment] 2019-08-30 11:47
Ah yes sorry, missed that part of your request. I think utilizing a single timer here will make things quite complicated. But lets see, maybe part of the memory leak fix will be removing the timer ;)

**Comment by edwh** [comment] 2019-08-30 11:49
(Don't answer this if you're too busy or the question reveals utter ignorance of what your plugin is for.)

Am I correct that it's registering this timer for every component destroy?  If so, is there not a way to tell whether this component actually does anything related to meta tags at all?

**Comment by pimlie** [comment] 2019-08-30 11:53
No, the mixin is added on all components in your app. But the mixin only adds a `beforeCreate` lifecycle hook, within that hook it checks whether `metaInfo` / `head` has been defined or not. If so, then it proceed with adding all the necessary hooks. See here for the big if responsible for that: https://github.com/nuxt/vue-meta/blob/master/src/shared/mixin.js#L32 (should refactor that to an early return for better readability I see).

**Comment by edwh** [comment] 2019-08-30 11:57
Quick debug say I'm passing that test for loads of components. I'll dig further.

**Comment by edwh** [comment] 2019-08-30 12:04
It looks like nuxt-i18n may be responsible for setting up something for SEO on each component, which in turn is causing you to register the hooks for all components, which then results in the timer thrash I see.

I don't need i18n in this project, so I'll see if I can remove it as a workaround.

**Comment by edwh** [comment] 2019-08-30 12:08
Yup, removing that plugin means that vue-meta only sets up the hooks in relevant places, and that means that the timer stuff isn't an issue in practice.

I'll raise an issue over on there to see if they can avoid doing that, though you might like to look at the scalability anyway.  Thanks very much for your help.

**Comment by AndrewBogdanovTSS** [comment] 2019-09-09 12:54
I don't use nuxt-i18n in my project, but still experiencing this issue with Nuxt 2.9.2. Seems like it's using vue-meta 2.2.1. I will add vue-meta 2.2.2 manually in the project and let you know whether it fixes an issue

**Comment by manniL** [comment] 2019-09-09 16:49
@AndrewBogdanovTSS 	yarn upgrade should to the trick

**Comment by AndrewBogdanovTSS** [comment] 2019-09-09 17:11
@manniL yes, after upgrading to v. 2.2.2 the issue seems to go away, thanks. Is it a stable solution or just a workaround that will be improved in the future?

**Comment by manniL** [comment] 2019-09-09 17:26
Nice!

I'd suggest https://github.com/nuxt/vue-meta/issues/442 and the linked vue issue for further reading.
