### ISSUE TITLE
Javascript onload hook

### ISSUE THREAD

**Issue by janesser** [nuxt/vue-meta#335] opened 2019-03-20 16:31 UTC
Hi folks,

we have a use-case where we are lazy loading some library, e.g. from component.mount().
Then we sleep for 100 millies and use some methods from the js-lib loaded.

The usage is from vue-components typescript and will place some result into one of the components properties.

https://stackoverflow.com/questions/16230886/trying-to-fire-the-onload-event-on-script-tag

Actually there is the 'onload' hook that could help here. Is there some example of vue-meta using the onload hook on a script-tag?

What would be required to enable vue-meta to do so?

Kind regards,
Jan

**Comment by pimlie** [comment] 2019-03-20 17:53
See #240, at the moment this is unfortunately not supported nor is it planned for v2.0

**Comment by manniL** [comment] 2019-03-21 10:21
Duplicate of #240

**Closed by manniL** 2019-03-21 10:21 UTC
Labels: duplicate, question
