### ISSUE TITLE
Can you remove a parent meta value?

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/vue-meta#288] opened 2018-12-03 20:17 UTC
Really a question, not an issue.  I set canonical at the App.vue level (root) but would like to remove the tag under certain conditions in child comps (like when we set something to noindex,nofollow).  

Is there any way for a child comp to remove the parent meta tag?  It seems like vmid would REPLACE it, but I'd like to totally nuke it.  I'd like to not use any trickery via Vuex and would like to stay in vue-meta land if possible :)

**Comment by pimlie** [comment] 2019-03-07 18:21
Unfortunately this is not possible. Do you have a suggestion how this would work? 

Eg currently vue-meta works by deepmerging all the metaInfo objects of the components on a page, which means by design that adding/overwriting works but deleting wont unless we introduce a special case of `meta.content === false`

**Comment by pimlie** [comment] 2019-03-08 10:16
@manniL Wdyt about this? I think #204 is similar

**Comment by manniL** [comment] 2019-03-08 10:57
@pimlie Not sure whether that would add too much complexity :thinking:

**Comment by pimlie** [comment] 2019-03-08 11:06
I think this should work by ignoring source when `source[contentKeyName] === false` or `source.innerHTML === false` in arrayMerge and when we delete data properties in getComponentOption when there are `false` so they dont get deepmerged.

**Comment by manniL** [comment] 2019-03-08 11:57
@pimlie I'd probably tend to use `null` for it as false could be a valid value :thinking: But yeah, that sounds like a decent approach :clap:

**Comment by pimlie** [comment] 2019-03-08 13:23
Is `false` a valid value or `'false'`? Because we actually need two falsy values to differentiate between nuking the parents vmid (this issue) or ignoring the childs (issue 204). I would propose to use null for this issue and false for 204, but you might have a better idea?

**Comment by manniL** [comment] 2019-03-08 13:44
@pimlie hmm. good question, don't know by heart.

hm.. couldn't we use `undefined` for "No content" and `null` (or `false`?) for nuking? :relaxed: 
I think that'd be closer to the semantic expressions for `undefined` and `null`

**Comment by pimlie** [comment] 2019-03-08 14:31
@manniL The only problem I have with `undefined` is that given `a = {}` then `a.content` is also undefined, which means you have to check for both key existence as key value. But will change it for 204

**Comment by manniL** [comment] 2019-03-08 14:33
@pimlie Do we have to distinguish between `a = {}` and `a = { content: undefined }`?

**Comment by hecktarzuli** [comment] 2019-03-08 14:37
It's possible I don't understand everything in this lib, but couldn't we just introduce functions or something vs magic values?  To me it would make a little more sense to call removeMeta(something) and resetMeta(something) vs setting a value to null, false, etc..

**Comment by pimlie** [comment] 2019-03-08 14:46
Hmm, maybe its code style preference but `a = {}` means to me implicit behaviour and `a = { content: undefined }` means explicit behaviour. Personally I often like the latter because you have to indicate that you want the app to behave in a certain manner so its less likely to do stuff you didnt expect (because you didnt read the docs and really just wanted a meta tag without content like meta charset). 

@hecktarzuli The problem with that is where are those functions defined and when are they called? If you have multiple branches with components which define metaInfo then vue-meta will merge all the metaInfo's into one single object. Are those functions called after all the merging has taken place or immediately when a parent and child are merged? And does it call both parent and child functions or only the one of the child? I agree that having functions is nicer but it complicate things and for vue-meta v3 we will probably refactor everything from the ground up anyway. So therefore using null, false is a quick and easy solution for now :)

**Closed** 2019-04-20 10:51 UTC
Labels: question, target: v2

**Comment by pimlie** [comment] 2019-04-20 13:08
This issue has been closed as changes for it are included in the [v2 release candidate](https://github.com/nuxt/vue-meta/releases/tag/v2.0.0-rc.0). Please help us testing the release candidate and report any follow-ups in a new issue

**Comment by hecktarzuli** [comment] 2019-04-22 17:00
We'll have to check it out, thank you!
